language: rust

before_script:
  - rustup component add rustfmt-preview
  - rustup component add clippy-preview
script:
  - cargo fmt -- --check
  - cargo clippy -- -Dwarnings
  - cargo build --verbose --all
